# Basic `dependabot.yml` file with
# minimum configuration for three package managers

version: 2
updates:
  # Enable version updates for pip
  - package-ecosystem: "pip"
    directory: "/src/backend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/src/frontend"
    schedule:
      interval: "weekly"
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/src/backend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/src/frontend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/src/github"
    schedule:
      interval: "weekly"
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    # You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.
    directory: "/"
    schedule:
      interval: "weekly"
